### ISSUE TITLE
the chip seq fails to initialize

### ISSUE THREAD

**Issue by amitpande74** [gdevailly/HeatStarSeq_gh#7]

**Comment by gdevailly** [comment]
Thanks for the feedback. I can confirm https://joshiweb.cbu.uib.no/HeatStarSeq_gh/application/heatchipseq/ is not launching as intended. I will investigate.

**Comment by gdevailly** [comment]
The production server is missing an R package. Sorry about that. It should be fixed in about a week.

**Comment by gdevailly** [comment]
I believe it is now fixed. The ChIPseq application looks like its working as intended.
